### ISSUE TITLE
拉了demo跑起来有个方法报错

### ISSUE THREAD

**Issue by Isaac-chip** [accforgit/vue-chart-tree#1]
![image](https://user-images.githubusercontent.com/42114454/120607930-38584180-c483-11eb-98f4-f4b533b283a7.png)

**Comment by accforgit** [comment]
@Isaac-chip 
你第一个编辑器标签中的这一句
import VueChartTree, { updatePartTree } from '../src/vue-chart-tree'
'../src/vue-chart-tree'这个文件中应该没有导出 updatePartTree 方法吧

**Comment by Isaac-chip** [comment]
.vue文件咋导出呀 我试了export也不行

**Comment by Isaac-chip** [comment]
循环引用util里面的

**Comment by accforgit** [comment]
@Isaac-chip 你这个问题不是我库的问题，对着我demo重新组织一下你自己的文件吧

**Comment by Isaac-chip** [comment]
好了 重新跑起来了 感谢回复
