### ISSUE TITLE
`.tree_node` class 下的 `white-space: nowrap;` 是必要的吗？

### ISSUE THREAD

**Issue by weineel** [accforgit/vue-chart-tree#5]
由于在 IE 浏览器中 `white-space:  initial` 是无效的，无法简单覆写 `white-space: nowrap;` 样式，导致无法换行。

![image](https://user-images.githubusercontent.com/13328625/144822876-58ebcf6b-a4fc-4edd-8e26-393d80837bd3.png)

是否可以去掉这个样式？

**Comment by accforgit** [comment]
@weineel 必要的，如果 white-space: initial 无效，那就把值换成明确点的，例如 normal

**Comment by weineel** [comment]
@accforgit 可以帮忙解释下吗？没有看到哪边依赖这个样式。

**Comment by accforgit** [comment]
@accforgit 在这个demo里，把 white-space 样式去掉就知道了https://accforgit.github.io/vue-chart-tree/index.html

**Comment by accforgit** [comment]
@weineel 在这个demo里，把 white-space 样式去掉就知道了https://accforgit.github.io/vue-chart-tree/index.html

**Comment by weineel** [comment]
@accforgit

我一开始用的 chrome 去掉确实没问题。

demo 在 IE 11 上打不开，我本地启动，在 IE 11 上去掉也是没问题的。

下面是我测试的所有浏览器的显示结果。

<table>
<tr>
	<td> 浏览器
	<td> 样式是否错乱
<tr>
	<td> chrome 96
	<td> 否
<tr>
	<td> IE 11
	<td> 否
<tr>
	<td> Firefox 91
	<td> 是
<tr>
	<td> Microsoft Edge
	<td> 是
<tr>
	<td> Safari
	<td> 是
</table>
